/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LabelPartnerInput = IDL.Record({
  'websiteLink' : IDL.Opt(IDL.Text),
  'labelName' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const LabelReleaseInput = IDL.Record({
  'labelId' : IDL.Nat,
  'streamingLink' : IDL.Text,
  'songTitle' : IDL.Text,
  'artworkUrl' : IDL.Text,
  'artistName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SaveArtistProfileInput = IDL.Record({
  'isApproved' : IDL.Bool,
  'instagramLink' : IDL.Text,
  'profilePhoto' : ExternalBlob,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'spotifyProfile' : IDL.Text,
  'youtubeChannelLink' : IDL.Text,
  'facebookLink' : IDL.Text,
  'appleProfile' : IDL.Text,
  'profilePhotoFilename' : IDL.Text,
  'stageName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ArtistProfile = IDL.Record({
  'id' : IDL.Text,
  'isApproved' : IDL.Bool,
  'instagramLink' : IDL.Text,
  'owner' : IDL.Principal,
  'profilePhoto' : ExternalBlob,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'spotifyProfile' : IDL.Text,
  'youtubeChannelLink' : IDL.Text,
  'facebookLink' : IDL.Text,
  'appleProfile' : IDL.Text,
  'profilePhotoFilename' : IDL.Text,
  'stageName' : IDL.Text,
});
export const LabelPartner = IDL.Record({
  'id' : IDL.Nat,
  'websiteLink' : IDL.Opt(IDL.Text),
  'labelName' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const LabelRelease = IDL.Record({
  'id' : IDL.Nat,
  'labelId' : IDL.Nat,
  'streamingLink' : IDL.Text,
  'songTitle' : IDL.Text,
  'artworkUrl' : IDL.Text,
  'artistName' : IDL.Text,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const SongStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
  'live' : IDL.Null,
});
export const ACRResult = IDL.Record({
  'statusCode' : IDL.Text,
  'music' : IDL.Text,
});
export const TrackMetadata = IDL.Record({
  'title' : IDL.Text,
  'artist' : IDL.Text,
  'featuredArtist' : IDL.Text,
  'composer' : IDL.Text,
  'producer' : IDL.Text,
  'lyricist' : IDL.Text,
  'audioFile' : ExternalBlob,
  'audioFilename' : IDL.Text,
});
export const SongSubmission = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'releaseType' : IDL.Text,
  'genre' : IDL.Text,
  'language' : IDL.Text,
  'releaseDate' : Time,
  'artwork' : ExternalBlob,
  'artworkFilename' : IDL.Text,
  'artist' : IDL.Text,
  'featuredArtist' : IDL.Text,
  'composer' : IDL.Text,
  'producer' : IDL.Text,
  'lyricist' : IDL.Text,
  'audioFile' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'additionalDetails' : IDL.Text,
  'status' : SongStatus,
  'adminRemarks' : IDL.Text,
  'adminComment' : IDL.Text,
  'submitter' : IDL.Principal,
  'timestamp' : Time,
  'discountCode' : IDL.Opt(IDL.Text),
  'acrResult' : IDL.Opt(ACRResult),
  'preSaveLink' : IDL.Opt(IDL.Text),
  'liveStreamLink' : IDL.Opt(IDL.Text),
  'musicVideoLink' : IDL.Opt(IDL.Text),
  'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
  'publicLink' : IDL.Opt(IDL.Text),
  'adminLiveLink' : IDL.Opt(IDL.Text),
  'isManuallyRejected' : IDL.Bool,
  'spotifyLink' : IDL.Opt(IDL.Text),
  'appleMusicLink' : IDL.Opt(IDL.Text),
});
export const SongSubmissionInput = IDL.Record({
  'title' : IDL.Text,
  'language' : IDL.Text,
  'releaseDate' : Time,
  'releaseType' : IDL.Text,
  'genre' : IDL.Text,
  'artworkBlob' : ExternalBlob,
  'artworkFilename' : IDL.Text,
  'artist' : IDL.Text,
  'featuredArtist' : IDL.Text,
  'composer' : IDL.Text,
  'producer' : IDL.Text,
  'lyricist' : IDL.Text,
  'audioBlob' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'additionalDetails' : IDL.Text,
  'discountCode' : IDL.Opt(IDL.Text),
  'albumTracks' : IDL.Opt(IDL.Vec(TrackMetadata)),
  'musicVideoLink' : IDL.Opt(IDL.Text),
  'spotifyLink' : IDL.Opt(IDL.Text),
  'appleMusicLink' : IDL.Opt(IDL.Text),
});
export const UserCategory = IDL.Variant({
  'generalArtist' : IDL.Null,
  'proArtist' : IDL.Null,
  'ultraArtist' : IDL.Null,
  'generalLabel' : IDL.Null,
  'proLabel' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'artistId' : IDL.Text,
  'category' : UserCategory,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLabelPartner' : IDL.Func([LabelPartnerInput], [IDL.Nat], []),
  'addLabelRelease' : IDL.Func([LabelReleaseInput], [IDL.Nat], []),
  'adminDeleteArtistProfile' : IDL.Func([IDL.Text], [], []),
  'adminEditArtistProfile' : IDL.Func(
      [IDL.Text, SaveArtistProfileInput],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArtistProfile' : IDL.Func([SaveArtistProfileInput], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteArtistProfile' : IDL.Func([IDL.Text], [], []),
  'deleteLabelPartner' : IDL.Func([IDL.Nat], [], []),
  'deleteLabelRelease' : IDL.Func([IDL.Nat], [], []),
  'doesUserHaveArtistProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllArtistProfileOwnersForAdmin' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getAllArtistProfilesForAdmin' : IDL.Func(
      [],
      [IDL.Vec(ArtistProfile)],
      ['query'],
    ),
  'getAllLabelPartners' : IDL.Func([], [IDL.Vec(LabelPartner)], ['query']),
  'getAllLabelReleases' : IDL.Func([], [IDL.Vec(LabelRelease)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getArtistProfileByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ArtistProfile)],
      ['query'],
    ),
  'getArtistProfileEditingAccessStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getArtistProfileIdByOwnerId' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getArtistProfilesByUserForAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ArtistProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getLabelReleases' : IDL.Func([IDL.Nat], [IDL.Vec(LabelRelease)], ['query']),
  'getMyArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isArtistProfileEditingEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setArtistProfileEditingAccess' : IDL.Func([IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'submitSong' : IDL.Func([SongSubmissionInput], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArtistProfile' : IDL.Func([IDL.Text, SaveArtistProfileInput], [], []),
  'updateLabelPartner' : IDL.Func([LabelPartner], [], []),
  'updateLabelRelease' : IDL.Func([LabelRelease], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getAllSubmissionsForAdmin' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
  'editSongSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
  'adminUpdateSubmission' : IDL.Func([IDL.Text, SongStatus, IDL.Text, IDL.Text], [], []),
  'adminSetSubmissionLive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminEditSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
  'adminDeleteSubmission' : IDL.Func([IDL.Text], [], []),
  'isUserBlockedSongSubmission' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isUserBlockedPodcastSubmission' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LabelPartnerInput = IDL.Record({
    'websiteLink' : IDL.Opt(IDL.Text),
    'labelName' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const LabelReleaseInput = IDL.Record({
    'labelId' : IDL.Nat,
    'streamingLink' : IDL.Text,
    'songTitle' : IDL.Text,
    'artworkUrl' : IDL.Text,
    'artistName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SaveArtistProfileInput = IDL.Record({
    'isApproved' : IDL.Bool,
    'instagramLink' : IDL.Text,
    'profilePhoto' : ExternalBlob,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'spotifyProfile' : IDL.Text,
    'youtubeChannelLink' : IDL.Text,
    'facebookLink' : IDL.Text,
    'appleProfile' : IDL.Text,
    'profilePhotoFilename' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ArtistProfile = IDL.Record({
    'id' : IDL.Text,
    'isApproved' : IDL.Bool,
    'instagramLink' : IDL.Text,
    'owner' : IDL.Principal,
    'profilePhoto' : ExternalBlob,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'spotifyProfile' : IDL.Text,
    'youtubeChannelLink' : IDL.Text,
    'facebookLink' : IDL.Text,
    'appleProfile' : IDL.Text,
    'profilePhotoFilename' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const LabelPartner = IDL.Record({
    'id' : IDL.Nat,
    'websiteLink' : IDL.Opt(IDL.Text),
    'labelName' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const LabelRelease = IDL.Record({
    'id' : IDL.Nat,
    'labelId' : IDL.Nat,
    'streamingLink' : IDL.Text,
    'songTitle' : IDL.Text,
    'artworkUrl' : IDL.Text,
    'artistName' : IDL.Text,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLabelPartner' : IDL.Func([LabelPartnerInput], [IDL.Nat], []),
    'addLabelRelease' : IDL.Func([LabelReleaseInput], [IDL.Nat], []),
    'adminDeleteArtistProfile' : IDL.Func([IDL.Text], [], []),
    'adminEditArtistProfile' : IDL.Func(
        [IDL.Text, SaveArtistProfileInput],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArtistProfile' : IDL.Func([SaveArtistProfileInput], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteArtistProfile' : IDL.Func([IDL.Text], [], []),
    'deleteLabelPartner' : IDL.Func([IDL.Nat], [], []),
    'deleteLabelRelease' : IDL.Func([IDL.Nat], [], []),
    'doesUserHaveArtistProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllArtistProfileOwnersForAdmin' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllArtistProfilesForAdmin' : IDL.Func(
        [],
        [IDL.Vec(ArtistProfile)],
        ['query'],
      ),
    'getAllLabelPartners' : IDL.Func([], [IDL.Vec(LabelPartner)], ['query']),
    'getAllLabelReleases' : IDL.Func([], [IDL.Vec(LabelRelease)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getArtistProfileByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ArtistProfile)],
        ['query'],
      ),
    'getArtistProfileEditingAccessStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getArtistProfileIdByOwnerId' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getArtistProfilesByUserForAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ArtistProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getLabelReleases' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LabelRelease)],
        ['query'],
      ),
    'getMyArtistProfiles' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isArtistProfileEditingEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setArtistProfileEditingAccess' : IDL.Func([IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'submitSong' : IDL.Func([SongSubmissionInput], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArtistProfile' : IDL.Func(
        [IDL.Text, SaveArtistProfileInput],
        [],
        [],
      ),
    'updateLabelPartner' : IDL.Func([LabelPartner], [], []),
    'updateLabelRelease' : IDL.Func([LabelRelease], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getAllSubmissionsForAdmin' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
  'editSongSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
  'adminUpdateSubmission' : IDL.Func([IDL.Text, SongStatus, IDL.Text, IDL.Text], [], []),
  'adminSetSubmissionLive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminEditSubmission' : IDL.Func([SongSubmissionEditInput], [], []),
  'adminDeleteSubmission' : IDL.Func([IDL.Text], [], []),
  'isUserBlockedSongSubmission' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isUserBlockedPodcastSubmission' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
