/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ArtistProfile {
  'id' : string,
  'isApproved' : boolean,
  'instagramLink' : string,
  'owner' : Principal,
  'profilePhoto' : ExternalBlob,
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'isVerified' : boolean,
  'spotifyProfile' : string,
  'youtubeChannelLink' : string,
  'facebookLink' : string,
  'appleProfile' : string,
  'profilePhotoFilename' : string,
  'stageName' : string,
}
export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface LabelPartner {
  'id' : bigint,
  'websiteLink' : [] | [string],
  'labelName' : string,
  'description' : string,
  'logoUrl' : string,
}
export interface LabelPartnerInput {
  'websiteLink' : [] | [string],
  'labelName' : string,
  'description' : string,
  'logoUrl' : string,
}
export interface LabelRelease {
  'id' : bigint,
  'labelId' : bigint,
  'streamingLink' : string,
  'songTitle' : string,
  'artworkUrl' : string,
  'artistName' : string,
}
export interface LabelReleaseInput {
  'labelId' : bigint,
  'streamingLink' : string,
  'songTitle' : string,
  'artworkUrl' : string,
  'artistName' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface SaveArtistProfileInput {
  'isApproved' : boolean,
  'instagramLink' : string,
  'profilePhoto' : ExternalBlob,
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'spotifyProfile' : string,
  'youtubeChannelLink' : string,
  'facebookLink' : string,
  'appleProfile' : string,
  'profilePhotoFilename' : string,
  'stageName' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type SongStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null } |
  { 'live' : null };
export interface ACRResult {
  'statusCode' : string,
  'music' : string,
}
export interface TrackMetadata {
  'title' : string,
  'artist' : string,
  'featuredArtist' : string,
  'composer' : string,
  'producer' : string,
  'lyricist' : string,
  'audioFile' : ExternalBlob,
  'audioFilename' : string,
}
export interface SongSubmission {
  'id' : string,
  'title' : string,
  'releaseType' : string,
  'genre' : string,
  'language' : string,
  'releaseDate' : Time,
  'artwork' : ExternalBlob,
  'artworkFilename' : string,
  'artist' : string,
  'featuredArtist' : string,
  'composer' : string,
  'producer' : string,
  'lyricist' : string,
  'audioFile' : ExternalBlob,
  'audioFilename' : string,
  'additionalDetails' : string,
  'status' : SongStatus,
  'adminRemarks' : string,
  'adminComment' : string,
  'submitter' : Principal,
  'timestamp' : Time,
  'discountCode' : [] | [string],
  'acrResult' : [] | [ACRResult],
  'preSaveLink' : [] | [string],
  'liveStreamLink' : [] | [string],
  'musicVideoLink' : [] | [string],
  'albumTracks' : [] | [Array<TrackMetadata>],
  'publicLink' : [] | [string],
  'adminLiveLink' : [] | [string],
  'isManuallyRejected' : boolean,
  'spotifyLink' : [] | [string],
  'appleMusicLink' : [] | [string],
  'customCLine' : [] | [string],
  'customPLine' : [] | [string],
  'premiumLabel' : [] | [string],
  'contentType' : [] | [string],
  'sunoTrackLink' : [] | [string],
  'sunoAgreementFile' : [] | [ExternalBlob],
  'sunoAgreementFilename' : [] | [string],
  'licenceFile' : [] | [ExternalBlob],
  'licenceFilename' : [] | [string],
  'contentId' : [] | [boolean],
  'callerTuneStartSecond' : [] | [number],
}
export interface SongSubmissionInput {
  'title' : string,
  'language' : string,
  'releaseDate' : Time,
  'releaseType' : string,
  'genre' : string,
  'artworkBlob' : ExternalBlob,
  'artworkFilename' : string,
  'artist' : string,
  'featuredArtist' : string,
  'composer' : string,
  'producer' : string,
  'lyricist' : string,
  'audioBlob' : ExternalBlob,
  'audioFilename' : string,
  'additionalDetails' : string,
  'discountCode' : [] | [string],
  'albumTracks' : [] | [Array<TrackMetadata>],
  'musicVideoLink' : [] | [string],
  'spotifyLink' : [] | [string],
  'appleMusicLink' : [] | [string],
  'customCLine' : [] | [string],
  'customPLine' : [] | [string],
  'premiumLabel' : [] | [string],
  'contentType' : [] | [string],
  'sunoTrackLink' : [] | [string],
  'sunoAgreementFile' : [] | [ExternalBlob],
  'sunoAgreementFilename' : [] | [string],
  'licenceFile' : [] | [ExternalBlob],
  'licenceFilename' : [] | [string],
  'contentId' : [] | [boolean],
  'callerTuneStartSecond' : [] | [number],
}
export interface SongSubmissionAdmin {
  'id' : string,
  'title' : string,
  'releaseType' : string,
  'genre' : string,
  'language' : string,
  'releaseDate' : Time,
  'artwork' : ExternalBlob,
  'artworkFilename' : string,
  'artist' : string,
  'featuredArtist' : string,
  'composer' : string,
  'producer' : string,
  'lyricist' : string,
  'audioFile' : ExternalBlob,
  'audioFilename' : string,
  'additionalDetails' : string,
  'status' : SongStatus,
  'adminRemarks' : string,
  'adminComment' : string,
  'submitter' : Principal,
  'timestamp' : Time,
  'discountCode' : [] | [string],
  'acrResult' : [] | [ACRResult],
  'preSaveLink' : [] | [string],
  'liveStreamLink' : [] | [string],
  'musicVideoLink' : [] | [string],
  'albumTracks' : [] | [Array<TrackMetadata>],
  'publicLink' : [] | [string],
  'adminLiveLink' : [] | [string],
  'isManuallyRejected' : boolean,
  'spotifyLink' : [] | [string],
  'appleMusicLink' : [] | [string],
  'monthlyListeners' : [] | [number],
  'revenue' : [] | [number],
  'customCLine' : [] | [string],
  'customPLine' : [] | [string],
  'premiumLabel' : [] | [string],
  'contentType' : [] | [string],
  'sunoTrackLink' : [] | [string],
  'sunoAgreementFile' : [] | [ExternalBlob],
  'sunoAgreementFilename' : [] | [string],
  'licenceFile' : [] | [ExternalBlob],
  'licenceFilename' : [] | [string],
  'contentId' : [] | [boolean],
  'callerTuneStartSecond' : [] | [number],
}
export interface SongSubmissionEditInput {
  'songSubmissionId' : string,
  'title' : string,
  'releaseType' : string,
  'genre' : string,
  'language' : string,
  'releaseDate' : Time,
  'artworkBlob' : ExternalBlob,
  'artworkFilename' : string,
  'artist' : string,
  'featuredArtist' : string,
  'composer' : string,
  'producer' : string,
  'lyricist' : string,
  'audioFile' : ExternalBlob,
  'audioFilename' : string,
  'additionalDetails' : string,
  'discountCode' : [] | [string],
  'musicVideoLink' : [] | [string],
  'albumTracks' : [] | [Array<TrackMetadata>],
  'spotifyLink' : [] | [string],
  'appleMusicLink' : [] | [string],
}
export type UserCategory = { 'generalArtist' : null } |
  { 'proArtist' : null } |
  { 'ultraArtist' : null } |
  { 'generalLabel' : null } |
  { 'proLabel' : null };
export interface AdminUserView {
  'principal' : Principal,
  'displayName' : string,
  'isAdmin' : boolean,
  'isTeamMember' : boolean,
  'isVerified' : boolean,
  'isSongBlocked' : boolean,
  'isPodcastBlocked' : boolean,
}
export interface UserProfile {
  'name' : string,
  'artistId' : string,
  'category' : UserCategory,
}
export type VideoSubmissionStatus = { 'pending' : null } | { 'approved' : null } | { 'rejected' : null } | { 'waiting' : null } | { 'live' : null };
export interface VideoSubmission {
  'id' : string,
  'userId' : Principal,
  'title' : string,
  'description' : string,
  'category' : string,
  'tags' : Array<string>,
  'thumbnail' : ExternalBlob,
  'artwork' : ExternalBlob,
  'videoFile' : ExternalBlob,
  'status' : VideoSubmissionStatus,
  'liveUrl' : [] | [string],
  'submittedAt' : Time,
  'updatedAt' : Time,
}
export interface VideoSubmissionInput {
  'title' : string,
  'description' : string,
  'category' : string,
  'tags' : Array<string>,
  'thumbnail' : ExternalBlob,
  'artwork' : ExternalBlob,
  'videoFile' : ExternalBlob,
}
export type PodcastModerationStatus = { 'pending' : null } | { 'approved' : null } | { 'live' : null } | { 'rejected' : null };
export type PodcastType = { 'audio' : null } | { 'video' : null };
export type EpisodeType = { 'trailer' : null } | { 'full' : null } | { 'bonus' : null };
export type PodcastCategory = { 'arts' : null } | { 'business' : null } | { 'comedy' : null } | { 'education' : null } | { 'healthFitness' : null } | { 'kidsFamily' : null } | { 'music' : null } | { 'newsPolitics' : null } | { 'religionSpirituality' : null } | { 'science' : null } | { 'sports' : null } | { 'technology' : null } | { 'tvFilm' : null } | { 'other' : null };
export type Language = { 'english' : null } | { 'hindi' : null } | { 'tamil' : null } | { 'telugu' : null } | { 'kannada' : null } | { 'malayalam' : null } | { 'punjabi' : null } | { 'bengali' : null } | { 'marathi' : null } | { 'gujarati' : null } | { 'other' : null };
export interface PodcastShow {
  'id' : string,
  'title' : string,
  'description' : string,
  'podcastType' : PodcastType,
  'category' : PodcastCategory,
  'language' : Language,
  'artwork' : ExternalBlob,
  'createdBy' : Principal,
  'timestamp' : Time,
  'moderationStatus' : PodcastModerationStatus,
  'liveLink' : [] | [string],
}
export interface PodcastEpisode {
  'id' : string,
  'showId' : string,
  'title' : string,
  'description' : string,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'episodeType' : EpisodeType,
  'isEighteenPlus' : boolean,
  'isExplicit' : boolean,
  'isPromotional' : boolean,
  'artwork' : ExternalBlob,
  'thumbnail' : ExternalBlob,
  'mediaFile' : ExternalBlob,
  'createdBy' : Principal,
  'timestamp' : Time,
  'moderationStatus' : PodcastModerationStatus,
}
export interface PodcastShowInput {
  'title' : string,
  'description' : string,
  'podcastType' : PodcastType,
  'category' : PodcastCategory,
  'language' : Language,
  'artwork' : ExternalBlob,
}
export interface PodcastEpisodeInput {
  'showId' : string,
  'title' : string,
  'description' : string,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'episodeType' : EpisodeType,
  'isEighteenPlus' : boolean,
  'isExplicit' : boolean,
  'isPromotional' : boolean,
  'artwork' : ExternalBlob,
  'thumbnail' : ExternalBlob,
  'mediaFile' : ExternalBlob,
}
export type VerificationStatus = { 'pending' : null } | { 'approved' : null } | { 'rejected' : null } | { 'waiting' : null };
export interface VerificationRequest {
  'id' : string,
  'user' : Principal,
  'status' : VerificationStatus,
  'timestamp' : Time,
  'verificationApprovedTimestamp' : [] | [Time],
  'expiryExtensionDays' : bigint,
}
export interface FeaturedArtistSong { 'title' : string, 'link' : string }
export interface FeaturedArtistInput {
  'artistName' : string,
  'photoUrl' : string,
  'aboutBlurb' : string,
  'songs' : Array<FeaturedArtistSong>,
  'isActive' : boolean,
}
export interface FeaturedArtist {
  'id' : bigint,
  'slotIndex' : bigint,
  'artistName' : string,
  'photoUrl' : string,
  'aboutBlurb' : string,
  'songs' : Array<FeaturedArtistSong>,
  'isActive' : boolean,
}
export interface TopVibingSong {
  'id' : bigint,
  'title' : string,
  'artistName' : string,
  'genre' : string,
  'artworkUrl' : string,
  'streamingLink' : string,
  'tagline' : [] | [string],
  'rank' : bigint,
}
export interface SubscriptionPlan {
  'planName' : string,
  'pricePerYear' : bigint,
  'redirectUrl' : string,
  'benefits' : Array<string>,
}
export interface MonthlyListenerStats { 'year' : bigint, 'month' : bigint, 'value' : bigint }
export interface PublicSongInfo {
  'id' : string,
  'title' : string,
  'artist' : string,
  'featuredArtist' : string,
  'artwork' : ExternalBlob,
  'spotifyLink' : [] | [string],
  'appleMusicLink' : [] | [string],
  'releaseDate' : Time,
  'genre' : string,
  'language' : string,
  'musicVideoLink' : [] | [string],
}
export type WithdrawStatus = { 'pending' : null } | { 'approved' : null } | { 'rejected' : null };
export interface WithdrawRequestInput {
  'fullName' : string,
  'googlePayAccountName' : string,
  'upiId' : string,
  'message' : string,
  'amount' : number,
  'qrCodeBlob' : ExternalBlob,
  'qrCodeFilename' : string,
}
export interface WithdrawRequest {
  'id' : string,
  'submitter' : Principal,
  'fullName' : string,
  'googlePayAccountName' : string,
  'upiId' : string,
  'message' : string,
  'amount' : number,
  'qrCodeBlob' : ExternalBlob,
  'qrCodeFilename' : string,
  'status' : WithdrawStatus,
  'rejectionReason' : string,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<[Array<Uint8Array>], undefined>,
  '_caffeineStorageCreateCertificate' : ActorMethod<[string], _CaffeineStorageCreateCertificateResult>,
  '_caffeineStorageRefillCashier' : ActorMethod<[[] | [_CaffeineStorageRefillInformation]], _CaffeineStorageRefillResult>,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLabelPartner' : ActorMethod<[LabelPartnerInput], bigint>,
  'addLabelRelease' : ActorMethod<[LabelReleaseInput], bigint>,
  'addTopVibingSong' : ActorMethod<[TopVibingSong], bigint>,
  'adminDeleteArtistProfile' : ActorMethod<[string], undefined>,
  'adminDeleteSubmission' : ActorMethod<[string], undefined>,
  'adminEditArtistProfile' : ActorMethod<[string, SaveArtistProfileInput], undefined>,
  'adminEditSubmission' : ActorMethod<[SongSubmissionEditInput], undefined>,
  'adminSetSubmissionLive' : ActorMethod<[string, string, string, string], undefined>,
  'adminUpdateSubmission' : ActorMethod<[string, SongStatus, string, string], undefined>,
  'adminUpdateSongStats' : ActorMethod<[string, [] | [number], [] | [number]], undefined>,
  'applyForVerification' : ActorMethod<[], string>,
  'approveEpisode' : ActorMethod<[string], undefined>,
  'approvePodcast' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUserPodcastSubmission' : ActorMethod<[Principal], undefined>,
  'blockUserSongSubmission' : ActorMethod<[Principal], undefined>,
  'createArtistProfile' : ActorMethod<[SaveArtistProfileInput], string>,
  'createCheckoutSession' : ActorMethod<[Array<ShoppingItem>, string, string], string>,
  'createPodcastEpisode' : ActorMethod<[PodcastEpisodeInput], string>,
  'createPodcastShow' : ActorMethod<[PodcastShowInput], string>,
  'createSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'deleteArtistProfile' : ActorMethod<[string], undefined>,
  'deleteLabelPartner' : ActorMethod<[bigint], undefined>,
  'deleteLabelRelease' : ActorMethod<[bigint], undefined>,
  'deleteSubscriptionPlan' : ActorMethod<[string], undefined>,
  'deleteTopVibingSong' : ActorMethod<[bigint], undefined>,
  'deleteVideoSubmission' : ActorMethod<[string], undefined>,
  'demoteFromAdmin' : ActorMethod<[Principal], undefined>,
  'doesUserHaveArtistProfile' : ActorMethod<[Principal], boolean>,
  'downgradeTeamMember' : ActorMethod<[Principal], undefined>,
  'downloadVideoFile' : ActorMethod<[string], [] | [ExternalBlob]>,
  'editSongSubmission' : ActorMethod<[SongSubmissionEditInput], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActiveFeaturedArtists' : ActorMethod<[], Array<FeaturedArtist>>,
  'getAllArtistProfileOwnersForAdmin' : ActorMethod<[], Array<Principal>>,
  'getAllArtistProfilesForAdmin' : ActorMethod<[], Array<ArtistProfile>>,
  'getAllBlockedUsersAdmin' : ActorMethod<[], Array<Principal>>,
  'getAllEpisodes' : ActorMethod<[], Array<PodcastEpisode>>,
  'getAllLabelPartners' : ActorMethod<[], Array<LabelPartner>>,
  'getAllLabelReleases' : ActorMethod<[], Array<LabelRelease>>,
  'getAllPendingEpisodes' : ActorMethod<[], Array<PodcastEpisode>>,
  'getAllPendingPodcasts' : ActorMethod<[], Array<PodcastShow>>,
  'getAllPodcasts' : ActorMethod<[], Array<PodcastShow>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllSubmissionsForAdmin' : ActorMethod<[], Array<SongSubmission>>,
  'getAllSubmissionsWithStatsForAdmin' : ActorMethod<[], Array<SongSubmissionAdmin>>,
  'getLiveSongsForAdmin' : ActorMethod<[], Array<SongSubmission>>,
  'getAllSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getAllRegisteredUsersForAdmin' : ActorMethod<[], Array<AdminUserView>>,
  'getAllTeamMembers' : ActorMethod<[], Array<Principal>>,
  'grantPremiumRole' : ActorMethod<[Principal], undefined>,
  'isCallerPremium' : ActorMethod<[], boolean>,
  'getAllPremiumUsers' : ActorMethod<[], Array<Principal>>,
  'getAllTopVibingSongs' : ActorMethod<[], Array<TopVibingSong>>,
  'getAllVideoSubmissions' : ActorMethod<[], Array<VideoSubmission>>,
  'getAnnouncement' : ActorMethod<[], string>,
  'getArtistProfileByOwner' : ActorMethod<[Principal], [] | [ArtistProfile]>,
  'getArtistProfileEditingAccessStatus' : ActorMethod<[], boolean>,
  'getArtistProfileIdByOwnerId' : ActorMethod<[Principal], [] | [string]>,
  'getArtistProfilesByUserForAdmin' : ActorMethod<[Principal], Array<ArtistProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEpisodesByShowId' : ActorMethod<[string], Array<PodcastEpisode>>,
  'getFeaturedArtists' : ActorMethod<[], Array<FeaturedArtist>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getLabelReleases' : ActorMethod<[bigint], Array<LabelRelease>>,
  'getMyArtistProfiles' : ActorMethod<[], Array<ArtistProfile>>,
  'getMyEpisodes' : ActorMethod<[string], Array<PodcastEpisode>>,
  'getMyPodcastShows' : ActorMethod<[], Array<PodcastShow>>,
  'getMySubmissions' : ActorMethod<[], Array<SongSubmission>>,
  'getPodcastsByCategory' : ActorMethod<[PodcastCategory], Array<PodcastShow>>,
  'getRankedTopVibingSongs' : ActorMethod<[], Array<TopVibingSong>>,
  'getSongInfo' : ActorMethod<[string], [] | [PublicSongInfo]>,
  'getSongMonthlyListenerStats' : ActorMethod<[string], Array<MonthlyListenerStats>>,
  'getSongRevenue' : ActorMethod<[string], number>,
  'getSongMonthlyListeners' : ActorMethod<[string], number>,
  'getAllSongRevenues' : ActorMethod<[], Array<[string, number]>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTopVibingSong' : ActorMethod<[bigint], [] | [TopVibingSong]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVideoSubmissions' : ActorMethod<[], Array<VideoSubmission>>,
  'getUsersByCategory' : ActorMethod<[UserCategory], Array<Principal>>,
  'getVerificationRequests' : ActorMethod<[], Array<VerificationRequest>>,
  'getVerificationRequestsByUser' : ActorMethod<[Principal], Array<VerificationRequest>>,
  'getWebsiteLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'handleVerificationRequest' : ActorMethod<[string, boolean, string, VerificationStatus], undefined>,
  'isArtistProfileEditingEnabled' : ActorMethod<[], boolean>,
  'isArtistVerified' : ActorMethod<[Principal], boolean>,
  'bootstrapAdmin' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserBlockedPodcastSubmission' : ActorMethod<[Principal], boolean>,
  'isUserBlockedSongSubmission' : ActorMethod<[Principal], boolean>,
  'isUserTeamMember' : ActorMethod<[Principal], boolean>,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markEpisodeLive' : ActorMethod<[string], undefined>,
  'markPodcastLive' : ActorMethod<[string, string], undefined>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'rejectEpisode' : ActorMethod<[string], undefined>,
  'rejectPodcast' : ActorMethod<[string], undefined>,
  'removeWebsiteLogo' : ActorMethod<[], undefined>,
  'reorderTopVibingSongs' : ActorMethod<[Array<bigint>], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAnnouncement' : ActorMethod<[string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setArtistProfileEditingAccess' : ActorMethod<[boolean], undefined>,
  'setFeaturedArtist' : ActorMethod<[bigint, FeaturedArtistInput], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWebsiteLogo' : ActorMethod<[ExternalBlob], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'submitSong' : ActorMethod<[SongSubmissionInput], string>,
  'submitVideo' : ActorMethod<[VideoSubmissionInput], string>,
  'toggleFeaturedArtistSlot' : ActorMethod<[bigint, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unblockUserPodcastSubmission' : ActorMethod<[Principal], undefined>,
  'unblockUserSongSubmission' : ActorMethod<[Principal], undefined>,
  'updateArtistProfile' : ActorMethod<[string, SaveArtistProfileInput], undefined>,
  'updateLabelPartner' : ActorMethod<[LabelPartner], undefined>,
  'updateLabelRelease' : ActorMethod<[LabelRelease], undefined>,
  'updateMonthlyListenerStats' : ActorMethod<[string, Array<MonthlyListenerStats>], undefined>,
  'setSongRevenue' : ActorMethod<[string, number], undefined>,
  'submitWithdrawRequest' : ActorMethod<[WithdrawRequestInput], string>,
  'getMyWithdrawRequests' : ActorMethod<[], Array<WithdrawRequest>>,
  'getAllWithdrawRequestsForAdmin' : ActorMethod<[], Array<WithdrawRequest>>,
  'approveWithdrawRequest' : ActorMethod<[string], undefined>,
  'rejectWithdrawRequest' : ActorMethod<[string, string], undefined>,
  'getWithdrawnAmountForUser' : ActorMethod<[], number>,

  'updateSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'updateTopVibingSong' : ActorMethod<[TopVibingSong], undefined>,
  'updateUserCategory' : ActorMethod<[Principal, UserCategory], undefined>,
  'updateVerificationStatus' : ActorMethod<[string, VerificationStatus, bigint], undefined>,
  'updateVideoStatus' : ActorMethod<[string, VideoSubmissionStatus, [] | [string]], undefined>,
  'updateVideoSubmission' : ActorMethod<[string, VideoSubmissionInput], undefined>,
  'upgradeUserToTeamMember' : ActorMethod<[Principal], undefined>,
  'revokePremiumRole' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
