/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ArtistProfile = IDL.Record({
  'isApproved' : IDL.Bool,
  'instagramLink' : IDL.Text,
  'profilePhoto' : ExternalBlob,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'spotifyProfile' : IDL.Text,
  'facebookLink' : IDL.Text,
  'appleProfile' : IDL.Text,
  'stageName' : IDL.Text,
});
export const SongStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const ACRResult = IDL.Record({
  'music' : IDL.Text,
  'statusCode' : IDL.Text,
});
export const SongSubmission = IDL.Record({
  'id' : IDL.Text,
  'status' : SongStatus,
  'title' : IDL.Text,
  'preSaveLink' : IDL.Opt(IDL.Text),
  'additionalDetails' : IDL.Text,
  'lyricist' : IDL.Text,
  'submitter' : IDL.Principal,
  'discountCode' : IDL.Opt(IDL.Text),
  'artworkFilename' : IDL.Text,
  'audioFile' : ExternalBlob,
  'artwork' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'language' : IDL.Text,
  'composer' : IDL.Text,
  'adminComment' : IDL.Text,
  'genre' : IDL.Text,
  'timestamp' : Time,
  'artist' : IDL.Text,
  'acrResult' : IDL.Opt(ACRResult),
  'producer' : IDL.Text,
  'releaseDate' : Time,
  'releaseType' : IDL.Text,
  'adminRemarks' : IDL.Text,
  'featuredArtist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPostInput = IDL.Record({
  'media' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PreSaveInput = IDL.Record({
  'preSaveLink' : IDL.Text,
  'songId' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Opt(ExternalBlob),
  'status' : IDL.Variant({ 'published' : IDL.Null, 'draft' : IDL.Null }),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'waiting' : IDL.Null,
});
export const VerificationRequestWithFullName = IDL.Record({
  'id' : IDL.Text,
  'status' : VerificationStatus,
  'expiryExtensionDays' : IDL.Nat,
  'user' : IDL.Principal,
  'fullName' : IDL.Text,
  'verificationApprovedTimestamp' : IDL.Opt(Time),
  'timestamp' : Time,
});
export const VerificationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : VerificationStatus,
  'expiryExtensionDays' : IDL.Nat,
  'user' : IDL.Principal,
  'verificationApprovedTimestamp' : IDL.Opt(Time),
  'timestamp' : Time,
});
export const AppUserRole = IDL.Variant({
  'admin' : IDL.Null,
  'team' : IDL.Null,
  'user' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'artistId' : IDL.Text,
});
export const CommunityMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'user' : IDL.Principal,
  'fullName' : IDL.Text,
  'timestamp' : Time,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SaveArtistProfileInput = IDL.Record({
  'isApproved' : IDL.Bool,
  'instagramLink' : IDL.Text,
  'profilePhoto' : ExternalBlob,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'spotifyProfile' : IDL.Text,
  'facebookLink' : IDL.Text,
  'appleProfile' : IDL.Text,
  'stageName' : IDL.Text,
});
export const CommunityMessageInput = IDL.Record({ 'content' : IDL.Text });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const SubmitSongInput = IDL.Record({
  'artworkBlob' : ExternalBlob,
  'title' : IDL.Text,
  'additionalDetails' : IDL.Text,
  'lyricist' : IDL.Text,
  'discountCode' : IDL.Opt(IDL.Text),
  'artworkFilename' : IDL.Text,
  'audioBlob' : ExternalBlob,
  'audioFilename' : IDL.Text,
  'language' : IDL.Text,
  'composer' : IDL.Text,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
  'producer' : IDL.Text,
  'releaseDate' : Time,
  'releaseType' : IDL.Text,
  'featuredArtist' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSongComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminEditArtistProfile' : IDL.Func([IDL.Principal, ArtistProfile], [], []),
  'adminEditSubmission' : IDL.Func([SongSubmission], [], []),
  'applyForVerification' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelVerificationRequest' : IDL.Func([], [], []),
  'createBlogPost' : IDL.Func([BlogPostInput], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPreSave' : IDL.Func([PreSaveInput], [IDL.Text], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deletePreSaveLink' : IDL.Func([IDL.Text], [], []),
  'deleteSubmission' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'downgradeTeamToUser' : IDL.Func([IDL.Principal], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAcrCloudResult' : IDL.Func([IDL.Text], [IDL.Opt(ACRResult)], ['query']),
  'getAllArtists' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
  'getAllArtistsWithUserIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ArtistProfile))],
      ['query'],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
  'getAllSubmissionsWithPreSaveLinks' : IDL.Func(
      [],
      [IDL.Vec(SongSubmission)],
      ['query'],
    ),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequestWithFullName)],
      ['query'],
    ),
  'getAllVerificationRequestsForMigration' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequestWithFullName)],
      ['query'],
    ),
  'getAllVerificationRequestsRaw' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'getAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
  'getAnnualMaintenanceFee' : IDL.Func([], [IDL.Int], ['query']),
  'getArtistProfile' : IDL.Func([], [IDL.Opt(ArtistProfile)], ['query']),
  'getArtistProfileByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ArtistProfile)],
      ['query'],
    ),
  'getArtistProfileEditingAccessStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerRole' : IDL.Func([], [AppUserRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityMessages' : IDL.Func([], [IDL.Vec(CommunityMessage)], ['query']),
  'getDashboardSummary' : IDL.Func([], [IDL.Text], ['query']),
  'getDistributionFee' : IDL.Func([], [IDL.Int], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getNextBatchOfMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CommunityMessage)],
      ['query'],
    ),
  'getPreSaveLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getPreloadedCommunityMessages' : IDL.Func(
      [],
      [IDL.Vec(CommunityMessage)],
      ['query'],
    ),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getSongComment' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubmission' : IDL.Func([IDL.Text], [SongSubmission], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [AppUserRole], ['query']),
  'getUserSubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
  'getVerificationStatus' : IDL.Func([], [VerificationStatus], ['query']),
  'hasCompleteArtistProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'isArtistProfileEditingEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerTeamMember' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserVerificationBadgeActive' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isVerificationBadgeActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isVerificationBadgeActiveWithExtensions' : IDL.Func(
      [IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'publishBlogPost' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveArtistProfile' : IDL.Func([SaveArtistProfileInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendCommunityMessage' : IDL.Func([CommunityMessageInput], [IDL.Text], []),
  'setAcrResult' : IDL.Func([IDL.Text, ACRResult], [], []),
  'setAnnualMaintenanceFee' : IDL.Func([IDL.Int], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setArtistProfileEditingAccess' : IDL.Func([IDL.Bool], [], []),
  'setDistributionFee' : IDL.Func([IDL.Int], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'submitSong' : IDL.Func([SubmitSongInput], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnnouncement' : IDL.Func([IDL.Text], [], []),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [], []),
  'updateSongSubmission' : IDL.Func([SongSubmission], [], []),
  'updateSubmissionStatus' : IDL.Func([IDL.Text, SongStatus, IDL.Text], [], []),
  'updateVerificationExpiryDays' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updateVerificationStatus' : IDL.Func(
      [IDL.Principal, VerificationStatus],
      [],
      [],
    ),
  'updateVerificationStatusWithData' : IDL.Func(
      [IDL.Text, VerificationStatus],
      [],
      [],
    ),
  'upgradeUserToTeam' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ArtistProfile = IDL.Record({
    'isApproved' : IDL.Bool,
    'instagramLink' : IDL.Text,
    'profilePhoto' : ExternalBlob,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'spotifyProfile' : IDL.Text,
    'facebookLink' : IDL.Text,
    'appleProfile' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const SongStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const ACRResult = IDL.Record({ 'music' : IDL.Text, 'statusCode' : IDL.Text });
  const SongSubmission = IDL.Record({
    'id' : IDL.Text,
    'status' : SongStatus,
    'title' : IDL.Text,
    'preSaveLink' : IDL.Opt(IDL.Text),
    'additionalDetails' : IDL.Text,
    'lyricist' : IDL.Text,
    'submitter' : IDL.Principal,
    'discountCode' : IDL.Opt(IDL.Text),
    'artworkFilename' : IDL.Text,
    'audioFile' : ExternalBlob,
    'artwork' : ExternalBlob,
    'audioFilename' : IDL.Text,
    'language' : IDL.Text,
    'composer' : IDL.Text,
    'adminComment' : IDL.Text,
    'genre' : IDL.Text,
    'timestamp' : Time,
    'artist' : IDL.Text,
    'acrResult' : IDL.Opt(ACRResult),
    'producer' : IDL.Text,
    'releaseDate' : Time,
    'releaseType' : IDL.Text,
    'adminRemarks' : IDL.Text,
    'featuredArtist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPostInput = IDL.Record({
    'media' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PreSaveInput = IDL.Record({
    'preSaveLink' : IDL.Text,
    'songId' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Opt(ExternalBlob),
    'status' : IDL.Variant({ 'published' : IDL.Null, 'draft' : IDL.Null }),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const VerificationRequestWithFullName = IDL.Record({
    'id' : IDL.Text,
    'status' : VerificationStatus,
    'expiryExtensionDays' : IDL.Nat,
    'user' : IDL.Principal,
    'fullName' : IDL.Text,
    'verificationApprovedTimestamp' : IDL.Opt(Time),
    'timestamp' : Time,
  });
  const VerificationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : VerificationStatus,
    'expiryExtensionDays' : IDL.Nat,
    'user' : IDL.Principal,
    'verificationApprovedTimestamp' : IDL.Opt(Time),
    'timestamp' : Time,
  });
  const AppUserRole = IDL.Variant({
    'admin' : IDL.Null,
    'team' : IDL.Null,
    'user' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'artistId' : IDL.Text });
  const CommunityMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'user' : IDL.Principal,
    'fullName' : IDL.Text,
    'timestamp' : Time,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SaveArtistProfileInput = IDL.Record({
    'isApproved' : IDL.Bool,
    'instagramLink' : IDL.Text,
    'profilePhoto' : ExternalBlob,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'spotifyProfile' : IDL.Text,
    'facebookLink' : IDL.Text,
    'appleProfile' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const CommunityMessageInput = IDL.Record({ 'content' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const SubmitSongInput = IDL.Record({
    'artworkBlob' : ExternalBlob,
    'title' : IDL.Text,
    'additionalDetails' : IDL.Text,
    'lyricist' : IDL.Text,
    'discountCode' : IDL.Opt(IDL.Text),
    'artworkFilename' : IDL.Text,
    'audioBlob' : ExternalBlob,
    'audioFilename' : IDL.Text,
    'language' : IDL.Text,
    'composer' : IDL.Text,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
    'producer' : IDL.Text,
    'releaseDate' : Time,
    'releaseType' : IDL.Text,
    'featuredArtist' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSongComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminEditArtistProfile' : IDL.Func([IDL.Principal, ArtistProfile], [], []),
    'adminEditSubmission' : IDL.Func([SongSubmission], [], []),
    'applyForVerification' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelVerificationRequest' : IDL.Func([], [], []),
    'createBlogPost' : IDL.Func([BlogPostInput], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPreSave' : IDL.Func([PreSaveInput], [IDL.Text], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deletePreSaveLink' : IDL.Func([IDL.Text], [], []),
    'deleteSubmission' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'downgradeTeamToUser' : IDL.Func([IDL.Principal], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAcrCloudResult' : IDL.Func([IDL.Text], [IDL.Opt(ACRResult)], ['query']),
    'getAllArtists' : IDL.Func([], [IDL.Vec(ArtistProfile)], ['query']),
    'getAllArtistsWithUserIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ArtistProfile))],
        ['query'],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
    'getAllSubmissionsWithPreSaveLinks' : IDL.Func(
        [],
        [IDL.Vec(SongSubmission)],
        ['query'],
      ),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequestWithFullName)],
        ['query'],
      ),
    'getAllVerificationRequestsForMigration' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequestWithFullName)],
        ['query'],
      ),
    'getAllVerificationRequestsRaw' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'getAnnouncement' : IDL.Func([], [IDL.Text], ['query']),
    'getAnnualMaintenanceFee' : IDL.Func([], [IDL.Int], ['query']),
    'getArtistProfile' : IDL.Func([], [IDL.Opt(ArtistProfile)], ['query']),
    'getArtistProfileByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ArtistProfile)],
        ['query'],
      ),
    'getArtistProfileEditingAccessStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerRole' : IDL.Func([], [AppUserRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityMessages' : IDL.Func(
        [],
        [IDL.Vec(CommunityMessage)],
        ['query'],
      ),
    'getDashboardSummary' : IDL.Func([], [IDL.Text], ['query']),
    'getDistributionFee' : IDL.Func([], [IDL.Int], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getNextBatchOfMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CommunityMessage)],
        ['query'],
      ),
    'getPreSaveLink' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getPreloadedCommunityMessages' : IDL.Func(
        [],
        [IDL.Vec(CommunityMessage)],
        ['query'],
      ),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getSongComment' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubmission' : IDL.Func([IDL.Text], [SongSubmission], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [AppUserRole], ['query']),
    'getUserSubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], ['query']),
    'getVerificationStatus' : IDL.Func([], [VerificationStatus], ['query']),
    'hasCompleteArtistProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'isArtistProfileEditingEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerTeamMember' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserVerificationBadgeActive' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isVerificationBadgeActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isVerificationBadgeActiveWithExtensions' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'publishBlogPost' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveArtistProfile' : IDL.Func([SaveArtistProfileInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendCommunityMessage' : IDL.Func([CommunityMessageInput], [IDL.Text], []),
    'setAcrResult' : IDL.Func([IDL.Text, ACRResult], [], []),
    'setAnnualMaintenanceFee' : IDL.Func([IDL.Int], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setArtistProfileEditingAccess' : IDL.Func([IDL.Bool], [], []),
    'setDistributionFee' : IDL.Func([IDL.Int], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'submitSong' : IDL.Func([SubmitSongInput], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnnouncement' : IDL.Func([IDL.Text], [], []),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [], []),
    'updateSongSubmission' : IDL.Func([SongSubmission], [], []),
    'updateSubmissionStatus' : IDL.Func(
        [IDL.Text, SongStatus, IDL.Text],
        [],
        [],
      ),
    'updateVerificationExpiryDays' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateVerificationStatus' : IDL.Func(
        [IDL.Principal, VerificationStatus],
        [],
        [],
      ),
    'updateVerificationStatusWithData' : IDL.Func(
        [IDL.Text, VerificationStatus],
        [],
        [],
      ),
    'upgradeUserToTeam' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };