/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    artistId: string;
}
export interface ArtistProfile {
    isApproved: boolean;
    instagramLink: string;
    profilePhoto: ExternalBlob;
    fullName: string;
    mobileNumber: string;
    email: string;
    spotifyProfile: string;
    facebookLink: string;
    appleProfile: string;
    stageName: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface SubmitSongInput {
    artworkBlob: ExternalBlob;
    title: string;
    additionalDetails: string;
    lyricist: string;
    discountCode?: string;
    artworkFilename: string;
    audioBlob: ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    genre: string;
    artist: string;
    producer: string;
    releaseDate: Time;
    releaseType: string;
    featuredArtist: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BlogPostInput {
    media?: ExternalBlob;
    title: string;
    content: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SaveArtistProfileInput {
    isApproved: boolean;
    instagramLink: string;
    profilePhoto: ExternalBlob;
    fullName: string;
    mobileNumber: string;
    email: string;
    spotifyProfile: string;
    facebookLink: string;
    appleProfile: string;
    stageName: string;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface PreSaveInput {
    preSaveLink: string;
    songId: string;
}
export interface CommunityMessageInput {
    content: string;
}
export interface CommunityMessage {
    id: string;
    content: string;
    role: string;
    user: Principal;
    fullName: string;
    timestamp: Time;
}
export interface BlogPost {
    id: string;
    media?: ExternalBlob;
    status: Variant_published_draft;
    title: string;
    content: string;
    author: Principal;
    timestamp: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface VerificationRequestWithFullName {
    id: string;
    status: VerificationStatus;
    expiryExtensionDays: bigint;
    user: Principal;
    fullName: string;
    verificationApprovedTimestamp?: Time;
    timestamp: Time;
}
export interface ACRResult {
    music: string;
    statusCode: string;
}
export interface SongSubmission {
    id: string;
    status: SongStatus;
    title: string;
    preSaveLink?: string;
    additionalDetails: string;
    lyricist: string;
    submitter: Principal;
    discountCode?: string;
    artworkFilename: string;
    audioFile: ExternalBlob;
    artwork: ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    adminComment: string;
    genre: string;
    timestamp: Time;
    artist: string;
    acrResult?: ACRResult;
    producer: string;
    releaseDate: Time;
    releaseType: string;
    adminRemarks: string;
    featuredArtist: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface VerificationRequest {
    id: string;
    status: VerificationStatus;
    expiryExtensionDays: bigint;
    user: Principal;
    verificationApprovedTimestamp?: Time;
    timestamp: Time;
}
export enum AppUserRole {
    admin = "admin",
    team = "team",
    user = "user"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum SongStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_published_draft {
    published = "published",
    draft = "draft"
}
export enum VerificationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    waiting = "waiting"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSongComment(songId: string, comment: string): Promise<void>;
    adminEditArtistProfile(artist: Principal, update: ArtistProfile): Promise<void>;
    adminEditSubmission(update: SongSubmission): Promise<void>;
    applyForVerification(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelVerificationRequest(): Promise<void>;
    createBlogPost(input: BlogPostInput): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPreSave(input: PreSaveInput): Promise<string>;
    deleteBlogPost(id: string): Promise<void>;
    deletePreSaveLink(songId: string): Promise<void>;
    deleteSubmission(id: string): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    downgradeTeamToUser(user: Principal): Promise<void>;
    generateInviteCode(): Promise<string>;
    getAcrCloudResult(songId: string): Promise<ACRResult | null>;
    getAllArtists(): Promise<Array<ArtistProfile>>;
    getAllArtistsWithUserIds(): Promise<Array<[Principal, ArtistProfile]>>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllSubmissions(): Promise<Array<SongSubmission>>;
    getAllSubmissionsWithPreSaveLinks(): Promise<Array<SongSubmission>>;
    getAllTeamMembers(): Promise<Array<Principal>>;
    getAllVerificationRequests(): Promise<Array<VerificationRequestWithFullName>>;
    getAllVerificationRequestsForMigration(): Promise<Array<VerificationRequestWithFullName>>;
    getAllVerificationRequestsRaw(): Promise<Array<VerificationRequest>>;
    getAnnouncement(): Promise<string>;
    getAnnualMaintenanceFee(): Promise<bigint>;
    getArtistProfile(): Promise<ArtistProfile | null>;
    getArtistProfileByUserId(user: Principal): Promise<ArtistProfile | null>;
    getArtistProfileEditingAccessStatus(): Promise<boolean>;
    getBlogPost(id: string): Promise<BlogPost | null>;
    getCallerRole(): Promise<AppUserRole>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunityMessages(): Promise<Array<CommunityMessage>>;
    getDashboardSummary(): Promise<string>;
    getDistributionFee(): Promise<bigint>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getNextBatchOfMessages(pageNumber: bigint): Promise<Array<CommunityMessage>>;
    getPreSaveLink(songId: string): Promise<string | null>;
    getPreloadedCommunityMessages(): Promise<Array<CommunityMessage>>;
    getPublishedBlogPosts(): Promise<Array<BlogPost>>;
    getSongComment(songId: string): Promise<string>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubmission(id: string): Promise<SongSubmission>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(user: Principal): Promise<AppUserRole>;
    getUserSubmissions(): Promise<Array<SongSubmission>>;
    getVerificationStatus(): Promise<VerificationStatus>;
    hasCompleteArtistProfile(): Promise<boolean>;
    isArtistProfileEditingEnabled(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isCallerTeamMember(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isUserVerificationBadgeActive(userId: Principal): Promise<boolean>;
    isVerificationBadgeActive(): Promise<boolean>;
    isVerificationBadgeActiveWithExtensions(user: Principal): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    publishBlogPost(id: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveArtistProfile(input: SaveArtistProfileInput): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendCommunityMessage(input: CommunityMessageInput): Promise<string>;
    setAcrResult(songId: string, acrResult: ACRResult): Promise<void>;
    setAnnualMaintenanceFee(fee: bigint): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setArtistProfileEditingAccess(enabled: boolean): Promise<void>;
    setDistributionFee(fee: bigint): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    submitSong(data: SubmitSongInput): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAnnouncement(announcement: string): Promise<void>;
    updateBlogPost(id: string, input: BlogPostInput): Promise<void>;
    updateSongSubmission(updatedSubmission: SongSubmission): Promise<void>;
    updateSubmissionStatus(id: string, status: SongStatus, remarks: string): Promise<void>;
    updateVerificationExpiryDays(userId: Principal, extraDays: bigint): Promise<void>;
    updateVerificationStatus(userId: Principal, newStatus: VerificationStatus): Promise<void>;
    updateVerificationStatusWithData(id: string, status: VerificationStatus): Promise<void>;
    upgradeUserToTeam(user: Principal): Promise<void>;
}
import type { ACRResult as _ACRResult, AppUserRole as _AppUserRole, ApprovalStatus as _ApprovalStatus, ArtistProfile as _ArtistProfile, BlogPost as _BlogPost, BlogPostInput as _BlogPostInput, ExternalBlob as _ExternalBlob, SaveArtistProfileInput as _SaveArtistProfileInput, SongStatus as _SongStatus, SongSubmission as _SongSubmission, StripeSessionStatus as _StripeSessionStatus, SubmitSongInput as _SubmitSongInput, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, VerificationRequest as _VerificationRequest, VerificationRequestWithFullName as _VerificationRequestWithFullName, VerificationStatus as _VerificationStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSongComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSongComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSongComment(arg0, arg1);
            return result;
        }
    }
    async adminEditArtistProfile(arg0: Principal, arg1: ArtistProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminEditArtistProfile(arg0, await to_candid_ArtistProfile_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminEditArtistProfile(arg0, await to_candid_ArtistProfile_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminEditSubmission(arg0: SongSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminEditSubmission(await to_candid_SongSubmission_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminEditSubmission(await to_candid_SongSubmission_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async applyForVerification(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForVerification();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForVerification();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelVerificationRequest(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelVerificationRequest();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelVerificationRequest();
            return result;
        }
    }
    async createBlogPost(arg0: BlogPostInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(await to_candid_BlogPostInput_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(await to_candid_BlogPostInput_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPreSave(arg0: PreSaveInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPreSave(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPreSave(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deletePreSaveLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreSaveLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreSaveLink(arg0);
            return result;
        }
    }
    async deleteSubmission(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async downgradeTeamToUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.downgradeTeamToUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downgradeTeamToUser(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAcrCloudResult(arg0: string): Promise<ACRResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcrCloudResult(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcrCloudResult(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllArtists(): Promise<Array<ArtistProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArtists();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArtists();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllArtistsWithUserIds(): Promise<Array<[Principal, ArtistProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArtistsWithUserIds();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArtistsWithUserIds();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<SongSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubmissionsWithPreSaveLinks(): Promise<Array<SongSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissionsWithPreSaveLinks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissionsWithPreSaveLinks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamMembers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamMembers();
            return result;
        }
    }
    async getAllVerificationRequests(): Promise<Array<VerificationRequestWithFullName>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVerificationRequests();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVerificationRequests();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVerificationRequestsForMigration(): Promise<Array<VerificationRequestWithFullName>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVerificationRequestsForMigration();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVerificationRequestsForMigration();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVerificationRequestsRaw(): Promise<Array<VerificationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVerificationRequestsRaw();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVerificationRequestsRaw();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnouncement(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncement();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncement();
            return result;
        }
    }
    async getAnnualMaintenanceFee(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnualMaintenanceFee();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnualMaintenanceFee();
            return result;
        }
    }
    async getArtistProfile(): Promise<ArtistProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtistProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtistProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtistProfileByUserId(arg0: Principal): Promise<ArtistProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtistProfileByUserId(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtistProfileByUserId(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtistProfileEditingAccessStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtistProfileEditingAccessStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtistProfileEditingAccessStatus();
            return result;
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRole(): Promise<AppUserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return from_candid_AppUserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return from_candid_AppUserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityMessages(): Promise<Array<CommunityMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityMessages();
            return result;
        }
    }
    async getDashboardSummary(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getDistributionFee(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistributionFee();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistributionFee();
            return result;
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getNextBatchOfMessages(arg0: bigint): Promise<Array<CommunityMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextBatchOfMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextBatchOfMessages(arg0);
            return result;
        }
    }
    async getPreSaveLink(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreSaveLink(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreSaveLink(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreloadedCommunityMessages(): Promise<Array<CommunityMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreloadedCommunityMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreloadedCommunityMessages();
            return result;
        }
    }
    async getPublishedBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogPosts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogPosts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongComment(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongComment(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: string): Promise<SongSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_SongSubmission_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_SongSubmission_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<AppUserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_AppUserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_AppUserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubmissions(): Promise<Array<SongSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubmissions();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubmissions();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerificationStatus(): Promise<VerificationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerificationStatus();
                return from_candid_VerificationStatus_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerificationStatus();
            return from_candid_VerificationStatus_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasCompleteArtistProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCompleteArtistProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCompleteArtistProfile();
            return result;
        }
    }
    async isArtistProfileEditingEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isArtistProfileEditingEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isArtistProfileEditingEnabled();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isCallerTeamMember(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerTeamMember();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerTeamMember();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isUserVerificationBadgeActive(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserVerificationBadgeActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserVerificationBadgeActive(arg0);
            return result;
        }
    }
    async isVerificationBadgeActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isVerificationBadgeActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isVerificationBadgeActive();
            return result;
        }
    }
    async isVerificationBadgeActiveWithExtensions(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isVerificationBadgeActiveWithExtensions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isVerificationBadgeActiveWithExtensions(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveArtistProfile(arg0: SaveArtistProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveArtistProfile(await to_candid_SaveArtistProfileInput_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveArtistProfile(await to_candid_SaveArtistProfileInput_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendCommunityMessage(arg0: CommunityMessageInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCommunityMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCommunityMessage(arg0);
            return result;
        }
    }
    async setAcrResult(arg0: string, arg1: ACRResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAcrResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAcrResult(arg0, arg1);
            return result;
        }
    }
    async setAnnualMaintenanceFee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAnnualMaintenanceFee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAnnualMaintenanceFee(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n62(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n62(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setArtistProfileEditingAccess(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setArtistProfileEditingAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setArtistProfileEditingAccess(arg0);
            return result;
        }
    }
    async setDistributionFee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDistributionFee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDistributionFee(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async submitSong(arg0: SubmitSongInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSong(await to_candid_SubmitSongInput_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSong(await to_candid_SubmitSongInput_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAnnouncement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: string, arg1: BlogPostInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, await to_candid_BlogPostInput_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, await to_candid_BlogPostInput_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSongSubmission(arg0: SongSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSongSubmission(await to_candid_SongSubmission_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSongSubmission(await to_candid_SongSubmission_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSubmissionStatus(arg0: string, arg1: SongStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SongStatus_n13(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SongStatus_n13(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateVerificationExpiryDays(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVerificationExpiryDays(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVerificationExpiryDays(arg0, arg1);
            return result;
        }
    }
    async updateVerificationStatus(arg0: Principal, arg1: VerificationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVerificationStatus(arg0, to_candid_VerificationStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVerificationStatus(arg0, to_candid_VerificationStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVerificationStatusWithData(arg0: string, arg1: VerificationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVerificationStatusWithData(arg0, to_candid_VerificationStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVerificationStatusWithData(arg0, to_candid_VerificationStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upgradeUserToTeam(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeUserToTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeUserToTeam(arg0);
            return result;
        }
    }
}
function from_candid_AppUserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
async function from_candid_ArtistProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArtistProfile): Promise<ArtistProfile> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_BlogPost_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SongStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SongStatus): SongStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_SongSubmission_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SongSubmission): Promise<SongSubmission> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationRequestWithFullName_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationRequestWithFullName): VerificationRequestWithFullName {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationRequest_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationRequest): VerificationRequest {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ACRResult]): ACRResult | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ArtistProfile]): Promise<ArtistProfile | null> {
    return value.length === 0 ? null : await from_candid_ArtistProfile_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isApproved: boolean;
    instagramLink: string;
    profilePhoto: _ExternalBlob;
    fullName: string;
    mobileNumber: string;
    email: string;
    spotifyProfile: string;
    facebookLink: string;
    appleProfile: string;
    stageName: string;
}): Promise<{
    isApproved: boolean;
    instagramLink: string;
    profilePhoto: ExternalBlob;
    fullName: string;
    mobileNumber: string;
    email: string;
    spotifyProfile: string;
    facebookLink: string;
    appleProfile: string;
    stageName: string;
}> {
    return {
        isApproved: value.isApproved,
        instagramLink: value.instagramLink,
        profilePhoto: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.profilePhoto),
        fullName: value.fullName,
        mobileNumber: value.mobileNumber,
        email: value.email,
        spotifyProfile: value.spotifyProfile,
        facebookLink: value.facebookLink,
        appleProfile: value.appleProfile,
        stageName: value.stageName
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: [] | [_ExternalBlob];
    status: {
        published: null;
    } | {
        draft: null;
    };
    title: string;
    content: string;
    author: Principal;
    timestamp: _Time;
}): Promise<{
    id: string;
    media?: ExternalBlob;
    status: Variant_published_draft;
    title: string;
    content: string;
    author: Principal;
    timestamp: Time;
}> {
    return {
        id: value.id,
        media: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.media)),
        status: from_candid_variant_n30(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        author: value.author,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SongStatus;
    title: string;
    preSaveLink: [] | [string];
    additionalDetails: string;
    lyricist: string;
    submitter: Principal;
    discountCode: [] | [string];
    artworkFilename: string;
    audioFile: _ExternalBlob;
    artwork: _ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    adminComment: string;
    genre: string;
    timestamp: _Time;
    artist: string;
    acrResult: [] | [_ACRResult];
    producer: string;
    releaseDate: _Time;
    releaseType: string;
    adminRemarks: string;
    featuredArtist: string;
}): Promise<{
    id: string;
    status: SongStatus;
    title: string;
    preSaveLink?: string;
    additionalDetails: string;
    lyricist: string;
    submitter: Principal;
    discountCode?: string;
    artworkFilename: string;
    audioFile: ExternalBlob;
    artwork: ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    adminComment: string;
    genre: string;
    timestamp: Time;
    artist: string;
    acrResult?: ACRResult;
    producer: string;
    releaseDate: Time;
    releaseType: string;
    adminRemarks: string;
    featuredArtist: string;
}> {
    return {
        id: value.id,
        status: from_candid_SongStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        preSaveLink: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.preSaveLink)),
        additionalDetails: value.additionalDetails,
        lyricist: value.lyricist,
        submitter: value.submitter,
        discountCode: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.discountCode)),
        artworkFilename: value.artworkFilename,
        audioFile: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.audioFile),
        artwork: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.artwork),
        audioFilename: value.audioFilename,
        language: value.language,
        composer: value.composer,
        adminComment: value.adminComment,
        genre: value.genre,
        timestamp: value.timestamp,
        artist: value.artist,
        acrResult: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.acrResult)),
        producer: value.producer,
        releaseDate: value.releaseDate,
        releaseType: value.releaseType,
        adminRemarks: value.adminRemarks,
        featuredArtist: value.featuredArtist
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _VerificationStatus;
    expiryExtensionDays: bigint;
    user: Principal;
    fullName: string;
    verificationApprovedTimestamp: [] | [_Time];
    timestamp: _Time;
}): {
    id: string;
    status: VerificationStatus;
    expiryExtensionDays: bigint;
    user: Principal;
    fullName: string;
    verificationApprovedTimestamp?: Time;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_VerificationStatus_n40(_uploadFile, _downloadFile, value.status),
        expiryExtensionDays: value.expiryExtensionDays,
        user: value.user,
        fullName: value.fullName,
        verificationApprovedTimestamp: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.verificationApprovedTimestamp)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _VerificationStatus;
    expiryExtensionDays: bigint;
    user: Principal;
    verificationApprovedTimestamp: [] | [_Time];
    timestamp: _Time;
}): {
    id: string;
    status: VerificationStatus;
    expiryExtensionDays: bigint;
    user: Principal;
    verificationApprovedTimestamp?: Time;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_VerificationStatus_n40(_uploadFile, _downloadFile, value.status),
        expiryExtensionDays: value.expiryExtensionDays,
        user: value.user,
        verificationApprovedTimestamp: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.verificationApprovedTimestamp)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n59(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
async function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _ArtistProfile]): Promise<[Principal, ArtistProfile]> {
    return [
        value[0],
        await from_candid_ArtistProfile_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): Variant_published_draft {
    return "published" in value ? Variant_published_draft.published : "draft" in value ? Variant_published_draft.draft : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
}): SongStatus {
    return "pending" in value ? SongStatus.pending : "approved" in value ? SongStatus.approved : "rejected" in value ? SongStatus.rejected : "draft" in value ? SongStatus.draft : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    waiting: null;
}): VerificationStatus {
    return "pending" in value ? VerificationStatus.pending : "approved" in value ? VerificationStatus.approved : "rejected" in value ? VerificationStatus.rejected : "waiting" in value ? VerificationStatus.waiting : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    team: null;
} | {
    user: null;
}): AppUserRole {
    return "admin" in value ? AppUserRole.admin : "team" in value ? AppUserRole.team : "user" in value ? AppUserRole.user : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n55(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArtistProfile>): Promise<Array<ArtistProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ArtistProfile_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _ArtistProfile]>): Promise<Array<[Principal, ArtistProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SongSubmission>): Promise<Array<SongSubmission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SongSubmission_n32(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VerificationRequestWithFullName>): Array<VerificationRequestWithFullName> {
    return value.map((x)=>from_candid_VerificationRequestWithFullName_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VerificationRequest>): Array<VerificationRequest> {
    return value.map((x)=>from_candid_VerificationRequest_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n57(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
async function to_candid_ArtistProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArtistProfile): Promise<_ArtistProfile> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_BlogPostInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPostInput): Promise<_BlogPostInput> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_SaveArtistProfileInput_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveArtistProfileInput): Promise<_SaveArtistProfileInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SongStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongStatus): _SongStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_SongSubmission_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongSubmission): Promise<_SongSubmission> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_SubmitSongInput_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitSongInput): Promise<_SubmitSongInput> {
    return await to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: SongStatus;
    title: string;
    preSaveLink?: string;
    additionalDetails: string;
    lyricist: string;
    submitter: Principal;
    discountCode?: string;
    artworkFilename: string;
    audioFile: ExternalBlob;
    artwork: ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    adminComment: string;
    genre: string;
    timestamp: Time;
    artist: string;
    acrResult?: ACRResult;
    producer: string;
    releaseDate: Time;
    releaseType: string;
    adminRemarks: string;
    featuredArtist: string;
}): Promise<{
    id: string;
    status: _SongStatus;
    title: string;
    preSaveLink: [] | [string];
    additionalDetails: string;
    lyricist: string;
    submitter: Principal;
    discountCode: [] | [string];
    artworkFilename: string;
    audioFile: _ExternalBlob;
    artwork: _ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    adminComment: string;
    genre: string;
    timestamp: _Time;
    artist: string;
    acrResult: [] | [_ACRResult];
    producer: string;
    releaseDate: _Time;
    releaseType: string;
    adminRemarks: string;
    featuredArtist: string;
}> {
    return {
        id: value.id,
        status: to_candid_SongStatus_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        preSaveLink: value.preSaveLink ? candid_some(value.preSaveLink) : candid_none(),
        additionalDetails: value.additionalDetails,
        lyricist: value.lyricist,
        submitter: value.submitter,
        discountCode: value.discountCode ? candid_some(value.discountCode) : candid_none(),
        artworkFilename: value.artworkFilename,
        audioFile: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.audioFile),
        artwork: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.artwork),
        audioFilename: value.audioFilename,
        language: value.language,
        composer: value.composer,
        adminComment: value.adminComment,
        genre: value.genre,
        timestamp: value.timestamp,
        artist: value.artist,
        acrResult: value.acrResult ? candid_some(value.acrResult) : candid_none(),
        producer: value.producer,
        releaseDate: value.releaseDate,
        releaseType: value.releaseType,
        adminRemarks: value.adminRemarks,
        featuredArtist: value.featuredArtist
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media?: ExternalBlob;
    title: string;
    content: string;
}): Promise<{
    media: [] | [_ExternalBlob];
    title: string;
    content: string;
}> {
    return {
        media: value.media ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.media)) : candid_none(),
        title: value.title,
        content: value.content
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    artworkBlob: ExternalBlob;
    title: string;
    additionalDetails: string;
    lyricist: string;
    discountCode?: string;
    artworkFilename: string;
    audioBlob: ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    genre: string;
    artist: string;
    producer: string;
    releaseDate: Time;
    releaseType: string;
    featuredArtist: string;
}): Promise<{
    artworkBlob: _ExternalBlob;
    title: string;
    additionalDetails: string;
    lyricist: string;
    discountCode: [] | [string];
    artworkFilename: string;
    audioBlob: _ExternalBlob;
    audioFilename: string;
    language: string;
    composer: string;
    genre: string;
    artist: string;
    producer: string;
    releaseDate: _Time;
    releaseType: string;
    featuredArtist: string;
}> {
    return {
        artworkBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.artworkBlob),
        title: value.title,
        additionalDetails: value.additionalDetails,
        lyricist: value.lyricist,
        discountCode: value.discountCode ? candid_some(value.discountCode) : candid_none(),
        artworkFilename: value.artworkFilename,
        audioBlob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.audioBlob),
        audioFilename: value.audioFilename,
        language: value.language,
        composer: value.composer,
        genre: value.genre,
        artist: value.artist,
        producer: value.producer,
        releaseDate: value.releaseDate,
        releaseType: value.releaseType,
        featuredArtist: value.featuredArtist
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isApproved: boolean;
    instagramLink: string;
    profilePhoto: ExternalBlob;
    fullName: string;
    mobileNumber: string;
    email: string;
    spotifyProfile: string;
    facebookLink: string;
    appleProfile: string;
    stageName: string;
}): Promise<{
    isApproved: boolean;
    instagramLink: string;
    profilePhoto: _ExternalBlob;
    fullName: string;
    mobileNumber: string;
    email: string;
    spotifyProfile: string;
    facebookLink: string;
    appleProfile: string;
    stageName: string;
}> {
    return {
        isApproved: value.isApproved,
        instagramLink: value.instagramLink,
        profilePhoto: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.profilePhoto),
        fullName: value.fullName,
        mobileNumber: value.mobileNumber,
        email: value.email,
        spotifyProfile: value.spotifyProfile,
        facebookLink: value.facebookLink,
        appleProfile: value.appleProfile,
        stageName: value.stageName
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
} {
    return value == SongStatus.pending ? {
        pending: null
    } : value == SongStatus.approved ? {
        approved: null
    } : value == SongStatus.rejected ? {
        rejected: null
    } : value == SongStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    waiting: null;
} {
    return value == VerificationStatus.pending ? {
        pending: null
    } : value == VerificationStatus.approved ? {
        approved: null
    } : value == VerificationStatus.rejected ? {
        rejected: null
    } : value == VerificationStatus.waiting ? {
        waiting: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
